from django.contrib.auth.views import (
    LogoutView,
    PasswordResetCompleteView,
    PasswordResetConfirmView,
    PasswordResetDoneView,
)
from django.urls import path

from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('grants', views.api_grants, name='api_grants_no_slash'),
    path('grants/', views.grants_list, name='grants_list'),
    path('grants/<int:pk>', views.api_grants, name='api_grant_detail_no_slash'),
    path('grants/<int:pk>/', views.grant_detail, name='grant_detail'),
    path('grants/<int:pk>/save/', views.save_grant, name='save_grant'),
    path('grants/<int:pk>/apply/', views.apply_grant, name='apply_grant'),
    path('register/', views.register, name='register'),
    path('register', views.register, name='register_no_slash'),
    path('login/', views.PortalLoginView.as_view(), name='login'),
    path('login', views.PortalLoginView.as_view(), name='login_no_slash'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('password-reset/', views.PortalPasswordResetView.as_view(), name='password_reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(template_name='portal/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name='portal/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(template_name='portal/password_reset_complete.html'), name='password_reset_complete'),
    path('profile/', views.profile, name='profile'),
    path('profile', views.api_profile, name='api_profile_no_slash'),
    path('my-applications/', views.my_applications, name='my_applications'),
    path('my-applications', views.api_my_applications, name='api_my_applications_no_slash'),
    path('saved-grants/', views.saved_grants, name='saved_grants'),
    path('recommendations/', views.recommendations, name='recommendations'),
    path('recommendations', views.api_recommendations, name='api_recommendations_no_slash'),
    path('notifications/', views.notifications, name='notifications'),
    path('notifications', views.api_notifications, name='api_notifications_no_slash'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('dashboard/export/excel/', views.export_excel, name='export_excel'),
    path('dashboard/grants/new/', views.grant_create, name='grant_create'),
    path('dashboard/grants/<int:pk>/edit/', views.grant_update, name='grant_update'),
    path('dashboard/grants/<int:pk>/delete/', views.grant_delete, name='grant_delete'),
    path('dashboard/applications/', views.manage_applications, name='manage_applications'),
    path('dashboard/applications/<int:pk>/status/', views.update_application_status, name='update_application_status'),
    path('dashboard/categories/', views.manage_categories, name='manage_categories'),
    path('dashboard/users/', views.users_list, name='users_list'),
    path('about/', views.about, name='about'),
    path('contacts/', views.contacts, name='contacts'),
    path('api/grants/', views.api_grants, name='api_grants'),
    path('api/grants/<int:pk>/', views.api_grants, name='api_grant_detail'),
    path('applications', views.api_create_application, name='api_create_application_no_slash'),
    path('applications/', views.api_create_application, name='api_create_application'),
    path('applications/<int:pk>/status', views.api_update_application_status, name='api_update_application_status_no_slash'),
    path('applications/<int:pk>/status/', views.api_update_application_status, name='api_update_application_status'),
    path('saved-grants', views.api_saved_grants, name='api_saved_grants_no_slash'),
    path('api/profile/', views.api_profile, name='api_profile'),
    path('api/my-applications/', views.api_my_applications, name='api_my_applications'),
    path('api/saved-grants/', views.api_saved_grants, name='api_saved_grants'),
    path('api/recommendations/', views.api_recommendations, name='api_recommendations'),
    path('api/notifications/', views.api_notifications, name='api_notifications'),
]
