# Generated by Django 5.2.1 on 2026-05-13 14:00

import django.db.models.deletion
import django.utils.timezone
import portal.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('full_name', models.CharField(max_length=180, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('role', models.CharField(choices=[('student', 'Студент'), ('admin', 'Администратор'), ('organization', 'Представитель организации')], default='student', max_length=20, verbose_name='Роль')),
                ('university', models.CharField(blank=True, max_length=180, verbose_name='Университет')),
                ('faculty', models.CharField(blank=True, max_length=180, verbose_name='Факультет')),
                ('course', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Курс')),
                ('education_level', models.CharField(blank=True, max_length=80, verbose_name='Уровень образования')),
                ('interests', models.CharField(blank=True, max_length=255, verbose_name='Интересы')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', portal.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('organization', models.CharField(max_length=180, verbose_name='Организатор')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('opportunity_type', models.CharField(choices=[('grant', 'Грант'), ('scholarship', 'Стипендия'), ('contest', 'Конкурс'), ('internship', 'Стажировка'), ('exchange', 'Обменная программа')], max_length=20, verbose_name='Тип возможности')),
                ('education_level', models.CharField(max_length=80, verbose_name='Уровень образования')),
                ('requirements', models.TextField(verbose_name='Требования')),
                ('documents', models.TextField(verbose_name='Документы')),
                ('deadline', models.DateField(verbose_name='Дедлайн')),
                ('official_link', models.URLField(verbose_name='Официальная ссылка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portal.category', verbose_name='Направление')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Грантовая возможность',
                'verbose_name_plural': 'Грантовые возможности',
                'ordering': ['deadline', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255, verbose_name='Сообщение')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv_file', models.FileField(blank=True, upload_to='applications/cv/', verbose_name='CV')),
                ('motivation_letter', models.FileField(blank=True, upload_to='applications/motivation/', verbose_name='Мотивационное письмо')),
                ('certificate_file', models.FileField(blank=True, upload_to='applications/certificates/', verbose_name='Сертификаты')),
                ('status', models.CharField(choices=[('review', 'На рассмотрении'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='review', max_length=20, verbose_name='Статус')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата подачи')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='portal.grant', verbose_name='Грант')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-submitted_at'],
                'unique_together': {('user', 'grant')},
            },
        ),
        migrations.CreateModel(
            name='SavedGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='portal.grant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сохраненный грант',
                'verbose_name_plural': 'Сохраненные гранты',
                'unique_together': {('user', 'grant')},
            },
        ),
    ]
